### ISSUE TITLE
[BUG] Incorrect `yellow_shulker_box.json`

### ISSUE THREAD

**Issue by RitikShah** [OrangeUtan/generator-beet#2]
You should be using this link: https://github.com/MinecraftPhi/MinecraftPhi-modules/blob/master/phi.modifyinv/src/datapack/data/minecraft/loot_tables/blocks/yellow_shulker_box.json

Instead of the one you are currently using. The datapack server is using the wrong loot table but they refuse to change it. The one linked above is the one used in most packs and originated from the MCC server.

**Comment by OrangeUtan** [comment]
Thanks, until recently I was not aware that there were multiple sources. In the future I will investigate more before adding features.
Beet actually has a built in Yellow-Shulker-Box plugin. Because adding it is literally just adding one line in the config file, I removed the feature for now.
I plan on replacing more features with beet plugins, making them easier to configure once the project is built.

I'm not quite sure yet, but eventually you can select a list of beet plugins you want to use. An advantage over just adding them manually could be convenvience or plugins from external sources (e.g. my custom babelbox plugin).

Feedback is always appreciated. Do you think this would be useful to you?

**Comment by OrangeUtan** [comment]
Fixed in cb54fb1362f4558f2f150035143de68f84349448 . Use the built-in beet plugin `yellow-shulkerbox`
